name: kodekid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.5
  http: ^1.1.0
  provider: ^6.1.1
  firebase_core: ^2.32.0
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/lessons/
    - assets/images/games/
    - assets/images/characters/
    - assets/images/ui/
    - assets/animations/
    - assets/sounds/
    - assets/icons/